https://www.youtube.com/watch?v=-hWKJulmVRI

# libraries

In [1]:
# pip install -Uqq torch==2.0.0

In [2]:
import torch as tr
 
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
 

In [3]:
tr.__version__

'2.1.2'

In [4]:
# check for GPU availability

tr.cuda.is_available()

True

In [5]:
# check for NVIDIA availability

!nvidia-smi

Wed May 29 12:11:10 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB           Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0              25W / 250W |      2MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [6]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.random.random([4,4])

array([[0.53649919, 0.20871553, 0.46535528, 0.58528326],
       [0.82416683, 0.06870308, 0.2997099 , 0.61208519],
       [0.62374397, 0.85083377, 0.20800248, 0.13769085],
       [0.16567029, 0.61574814, 0.63251312, 0.21111859]])

In [8]:
# generate random integer values between 3 and 60 of 3X3 matrix

np.random.randint(low=3,high=60,size=[3,3]) 

array([[39,  6, 44],
       [11, 29, 47],
       [24, 34, 16]])

In [9]:
np.random.random([4,4,4])

array([[[0.92048508, 0.71264516, 0.6611916 , 0.43521767],
        [0.35386471, 0.3391483 , 0.76814968, 0.11291985],
        [0.9176771 , 0.5728869 , 0.95991801, 0.59016925],
        [0.01251886, 0.52979104, 0.48318362, 0.55193237]],

       [[0.09606358, 0.61116788, 0.5942136 , 0.91388937],
        [0.09703349, 0.44033122, 0.82014154, 0.76478417],
        [0.92624417, 0.8326894 , 0.49532774, 0.09928504],
        [0.50314742, 0.39095703, 0.63355218, 0.18451445]],

       [[0.84892505, 0.94956866, 0.89384671, 0.95935126],
        [0.03428008, 0.88852995, 0.25116862, 0.19051724],
        [0.45509103, 0.47614495, 0.22344466, 0.90240114],
        [0.71637424, 0.42707571, 0.48043874, 0.74501013]],

       [[0.64727324, 0.07737993, 0.81294556, 0.13623413],
        [0.47659222, 0.70995278, 0.02000775, 0.02838072],
        [0.45837383, 0.4992739 , 0.34408771, 0.45193249],
        [0.46748454, 0.96128374, 0.83596479, 0.86834337]]])

# in torch

In [10]:
tr.ones([4,4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
tr.ones(4,4,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
rubiks = tr.ones(3,3,3,110) # a rubiks cube 3X3X3 and over a time of 110 steps
rubiks

tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]],


        [[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]],


        [[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1

In [13]:
rubiks[0,1,:]

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1

In [14]:
cub1 = tr.rand(4,4)
cub2 = tr.rand(4,4)
cub1,cub2

(tensor([[0.7032, 0.1599, 0.7671, 0.4091],
         [0.3409, 0.5874, 0.6837, 0.0472],
         [0.2569, 0.4356, 0.5441, 0.9230],
         [0.1229, 0.9409, 0.5616, 0.6949]]),
 tensor([[0.5543, 0.1652, 0.2411, 0.5457],
         [0.8860, 0.5013, 0.9313, 0.5945],
         [0.2104, 0.4024, 0.9001, 0.1984],
         [0.6890, 0.6046, 0.9529, 0.4048]]))

In [15]:
cub1+cub2

tensor([[1.2575, 0.3251, 1.0082, 0.9549],
        [1.2269, 1.0887, 1.6151, 0.6417],
        [0.4673, 0.8381, 1.4442, 1.1214],
        [0.8119, 1.5455, 1.5145, 1.0997]])