https://www.youtube.com/watch?v=-hWKJulmVRI

# libraries

In [2]:
# pip install -Uqq torch==2.0.0

In [9]:
import torch as tr
 
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
 

In [4]:
tr.__version__

'2.1.2'

In [8]:
# check for GPU availability

tr.cuda.is_available()

True

In [7]:
# check for NVIDIA availability

!nvidia-smi

Wed May 29 11:49:24 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB           Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P0              26W / 250W |      2MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [10]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.random.random([4,4])

array([[0.14523708, 0.0677883 , 0.23663388, 0.28283335],
       [0.67128891, 0.23460616, 0.57445388, 0.89898285],
       [0.73054683, 0.11994081, 0.04890883, 0.22534599],
       [0.88782772, 0.26540066, 0.0561061 , 0.95302151]])

In [15]:
# generate random integer values between 3 and 60 of 3X3 matrix

np.random.randint(low=3,high=60,size=[3,3]) 

array([[23, 57, 47],
       [14, 13, 20],
       [35,  7,  9]])

In [14]:
np.random.random([4,4,4])

array([[[0.71003844, 0.53685777, 0.74524601, 0.98255658],
        [0.03512841, 0.82445729, 0.57341731, 0.01486594],
        [0.56808315, 0.50167983, 0.18722676, 0.13682951],
        [0.9866808 , 0.79167982, 0.85252741, 0.58552731]],

       [[0.93981014, 0.13291368, 0.77311869, 0.74707639],
        [0.01873522, 0.79223946, 0.57123356, 0.79062177],
        [0.20549494, 0.31243049, 0.34047574, 0.66705966],
        [0.31994302, 0.49636544, 0.89992682, 0.02560602]],

       [[0.21684034, 0.18561468, 0.88194272, 0.08661484],
        [0.07986662, 0.79708589, 0.34621756, 0.74608181],
        [0.43844674, 0.14130783, 0.49742178, 0.92252011],
        [0.72717747, 0.79499837, 0.05255278, 0.88199578]],

       [[0.74124174, 0.07354964, 0.12207388, 0.82605924],
        [0.68353308, 0.74971773, 0.19608849, 0.1530054 ],
        [0.98956747, 0.75385876, 0.82006322, 0.49493909],
        [0.2474965 , 0.6130478 , 0.00833374, 0.58731573]]])

# in torch

In [16]:
tr.ones([4,4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
tr.ones(4,4,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [19]:
rubiks = tr.ones(3,3,3,110) # a rubiks cube 3X3X3 and over a time of 110 steps
rubiks

tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]],


        [[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]],


        [[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1

In [21]:
rubiks[0,1,:]

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1

In [23]:
cub1 = tr.rand(4,4)
cub2 = tr.rand(4,4)
cub1,cub2

(tensor([[0.5543, 0.2578, 0.3323, 0.6625],
         [0.6717, 0.1144, 0.7116, 0.1104],
         [0.5360, 0.1474, 0.3348, 0.1093],
         [0.0640, 0.3312, 0.2936, 0.8378]]),
 tensor([[0.6158, 0.6734, 0.3127, 0.2940],
         [0.2801, 0.8132, 0.1514, 0.4674],
         [0.4747, 0.4475, 0.8659, 0.8499],
         [0.6009, 0.4890, 0.1551, 0.1116]]))

In [24]:
cub1+cub2

tensor([[1.1701, 0.9313, 0.6450, 0.9565],
        [0.9518, 0.9276, 0.8629, 0.5778],
        [1.0107, 0.5949, 1.2007, 0.9592],
        [0.6649, 0.8202, 0.4487, 0.9494]])

# tensors on GPU
GPU are good for procesing the above arrays/tensors for a large scale

In [25]:
my_torch_array = tr.rand(3,3)
my_torch_array

tensor([[0.1684, 0.5220, 0.0828],
        [0.0143, 0.1690, 0.5799],
        [0.9712, 0.9898, 0.8808]])

In [26]:
my_torch_array.device

device(type='cpu')

In [29]:
my_torch_array=my_torch_array.to('cuda:0')
my_torch_array

tensor([[0.1684, 0.5220, 0.0828],
        [0.0143, 0.1690, 0.5799],
        [0.9712, 0.9898, 0.8808]], device='cuda:0')

In [31]:
my_torch_array2 = tr.rand(3,3)


In [33]:
# this will not work  as both of them on different devices
# my_torch_array+my_torch_array2

In [34]:
my_torch_array2 =my_torch_array2.to('cuda:0')
my_torch_array2

tensor([[0.1629, 0.6241, 0.9681],
        [0.1729, 0.7816, 0.9157],
        [0.3063, 0.0368, 0.7064]], device='cuda:0')

In [35]:
my_torch_array+my_torch_array2

tensor([[0.3313, 1.1462, 1.0509],
        [0.1872, 0.9506, 1.4956],
        [1.2775, 1.0267, 1.5872]], device='cuda:0')

In [36]:
%%timeit
my_torch_array+my_torch_array2

8.23 µs ± 76.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# cards dataset

In [38]:
train_path = '/kaggle/input/cards-image-datasetclassification/train'
test_path = '/kaggle/input/cards-image-datasetclassification/test'
valid_path = '/kaggle/input/cards-image-datasetclassification/valid'